using YoutubeMusicPlayer.Application.Interfaces;

namespace YoutubeMusicPlayer.Application.DTOs;

public class SearchResultDto
{
    public string Title { get; set; } = string.Empty;
    public string Author { get; set; } = string.Empty;
    public string Thumbnail { get; set; } = string.Empty;
    public string Type { get; set; } = "Song"; // Song, Artist, Album
    public string? VideoId { get; set; }
    public int? ArtistId { get; set; }
    public int? AlbumId { get; set; }
    public string? ExternalId { get; set; }
    public string? Source { get; set; } // Deezer, iTunes, Internal
    public bool IsVerified { get; set; }
}

public class PlaybackStreamDto
{
    public string? StreamUrl { get; set; }
    public string? VideoId { get; set; } // Added this
    public int? SongId { get; set; }
    public bool IsLiked { get; set; }
    public bool ShowAd { get; set; }
    public string? Error { get; set; }
    public string? Message { get; set; }
    public string? Title { get; set; }
    public string? Author { get; set; }
    public string? ThumbnailUrl { get; set; }
}

public class CaptionTrackDto
{
    public string LanguageCode { get; set; } = string.Empty;
    public string LanguageName { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
}

public class RichMetadataDto
{
    public string Lyrics { get; set; } = string.Empty;
    public List<TimedLyricLine>? TimedLyrics { get; set; }
    public string Bio { get; set; } = string.Empty;
    public string Status { get; set; } = "SUCCESS";
    public string LyricsType { get; set; } = "PLAIN"; // TIMED, PLAIN
    public List<CaptionTrackDto> AvailableCaptions { get; set; } = new();
}
