CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE albums (
    albumid integer GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    albumtype text,
    coverimageurl text,
    releasedate timestamp with time zone,
    recordlabel text,
    copyrighttext text,
    upc text,
    isexplicit boolean NOT NULL,
    deezer_album_id text,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_albums" PRIMARY KEY (albumid)
);

CREATE TABLE artists (
    artistid integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    bio text,
    country text,
    avatarurl text,
    bannerurl text,
    isverified boolean NOT NULL,
    subscribercount integer NOT NULL,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_artists" PRIMARY KEY (artistid)
);

CREATE TABLE categories (
    categoryid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description text,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_categories" PRIMARY KEY (categoryid)
);

CREATE TABLE genres (
    genreid integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text,
    CONSTRAINT "PK_genres" PRIMARY KEY (genreid)
);

CREATE TABLE subscription_plans (
    planid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    price numeric NOT NULL,
    duration_days integer NOT NULL,
    description text,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_subscription_plans" PRIMARY KEY (planid)
);

CREATE TABLE user_genre_stats (
    statid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    genre_name character varying(100) NOT NULL,
    listen_seconds double precision NOT NULL,
    updatedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_genre_stats" PRIMARY KEY (statid)
);

CREATE TABLE users (
    userid integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    passwordhash text,
    googleid text,
    role character varying(50) NOT NULL,
    avatarurl text,
    createdat timestamp with time zone NOT NULL,
    dateofbirth timestamp with time zone,
    ispremium boolean NOT NULL,
    islocked boolean NOT NULL,
    total_listen_seconds double precision NOT NULL,
    resettoken text,
    resettokenexpiry timestamp with time zone,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (userid)
);

CREATE TABLE albumartists (
    albumid integer NOT NULL,
    artistid integer NOT NULL,
    role text,
    CONSTRAINT "PK_albumartists" PRIMARY KEY (albumid, artistid),
    CONSTRAINT "FK_albumartists_albums_albumid" FOREIGN KEY (albumid) REFERENCES albums (albumid) ON DELETE CASCADE,
    CONSTRAINT "FK_albumartists_artists_artistid" FOREIGN KEY (artistid) REFERENCES artists (artistid) ON DELETE CASCADE
);

CREATE TABLE songs (
    songid integer GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    albumid integer,
    categoryid integer,
    duration integer,
    releasedate timestamp with time zone,
    youtubevideoid text NOT NULL,
    thumbnailurl text,
    lyricstext text,
    lyricssyncurl text,
    isrc text,
    isexplicit boolean NOT NULL,
    playcount bigint NOT NULL,
    ispremiumonly boolean NOT NULL,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_songs" PRIMARY KEY (songid),
    CONSTRAINT "FK_songs_albums_albumid" FOREIGN KEY (albumid) REFERENCES albums (albumid) ON DELETE SET NULL,
    CONSTRAINT "FK_songs_categories_categoryid" FOREIGN KEY (categoryid) REFERENCES categories (categoryid)
);

CREATE TABLE artist_followers (
    userid integer NOT NULL,
    artistid integer NOT NULL,
    followedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_artist_followers" PRIMARY KEY (userid, artistid),
    CONSTRAINT "FK_artist_followers_artists_artistid" FOREIGN KEY (artistid) REFERENCES artists (artistid) ON DELETE CASCADE,
    CONSTRAINT "FK_artist_followers_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE notifications (
    notificationid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer,
    title text NOT NULL,
    message text NOT NULL,
    type text,
    isread boolean NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_notifications" PRIMARY KEY (notificationid),
    CONSTRAINT "FK_notifications_users_userid" FOREIGN KEY (userid) REFERENCES users (userid)
);

CREATE TABLE payments (
    paymentid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    planid integer NOT NULL,
    amount numeric NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    status character varying(50) NOT NULL,
    order_code bigint NOT NULL,
    payos_transaction_id text,
    CONSTRAINT "PK_payments" PRIMARY KEY (paymentid),
    CONSTRAINT "FK_payments_subscription_plans_planid" FOREIGN KEY (planid) REFERENCES subscription_plans (planid) ON DELETE CASCADE,
    CONSTRAINT "FK_payments_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE playlists (
    playlistid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer,
    isfeatured boolean NOT NULL,
    featuredtype text,
    title character varying(255) NOT NULL,
    description text,
    coverimageurl text,
    visibility text NOT NULL,
    createdat timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_playlists" PRIMARY KEY (playlistid),
    CONSTRAINT "FK_playlists_users_userid" FOREIGN KEY (userid) REFERENCES users (userid)
);

CREATE TABLE reports (
    reportid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    targettype text NOT NULL,
    targetid text NOT NULL,
    reason text NOT NULL,
    details text,
    status text NOT NULL,
    createdat timestamp with time zone NOT NULL,
    resolvedat timestamp with time zone,
    CONSTRAINT "PK_reports" PRIMARY KEY (reportid),
    CONSTRAINT "FK_reports_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE user_subscriptions (
    user_subscription_id integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    planid integer NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_user_subscriptions" PRIMARY KEY (user_subscription_id),
    CONSTRAINT "FK_user_subscriptions_subscription_plans_planid" FOREIGN KEY (planid) REFERENCES subscription_plans (planid) ON DELETE CASCADE,
    CONSTRAINT "FK_user_subscriptions_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE usersearchhistory (
    searchid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    searchquery character varying(255) NOT NULL,
    searchedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_usersearchhistory" PRIMARY KEY (searchid),
    CONSTRAINT "FK_usersearchhistory_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE usersessions (
    sessionid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    token character varying(255) NOT NULL,
    expiresat timestamp with time zone NOT NULL,
    createdat timestamp with time zone NOT NULL,
    isrevoked boolean NOT NULL,
    CONSTRAINT "PK_usersessions" PRIMARY KEY (sessionid),
    CONSTRAINT "FK_usersessions_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE comments (
    commentid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    songid integer NOT NULL,
    content text NOT NULL,
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone,
    parentcommentid integer,
    CONSTRAINT "PK_comments" PRIMARY KEY (commentid),
    CONSTRAINT "FK_comments_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE,
    CONSTRAINT "FK_comments_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE listeninghistory (
    historyid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    songid integer NOT NULL,
    listenedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_listeninghistory" PRIMARY KEY (historyid),
    CONSTRAINT "FK_listeninghistory_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE,
    CONSTRAINT "FK_listeninghistory_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE songartists (
    songid integer NOT NULL,
    artistid integer NOT NULL,
    role text,
    CONSTRAINT "PK_songartists" PRIMARY KEY (songid, artistid),
    CONSTRAINT "FK_songartists_artists_artistid" FOREIGN KEY (artistid) REFERENCES artists (artistid) ON DELETE CASCADE,
    CONSTRAINT "FK_songartists_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE
);

CREATE TABLE songgenres (
    songid integer NOT NULL,
    genreid integer NOT NULL,
    CONSTRAINT "PK_songgenres" PRIMARY KEY (songid, genreid),
    CONSTRAINT "FK_songgenres_genres_genreid" FOREIGN KEY (genreid) REFERENCES genres (genreid) ON DELETE CASCADE,
    CONSTRAINT "FK_songgenres_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE
);

CREATE TABLE songlikes (
    userid integer NOT NULL,
    songid integer NOT NULL,
    likedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_songlikes" PRIMARY KEY (userid, songid),
    CONSTRAINT "FK_songlikes_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE,
    CONSTRAINT "FK_songlikes_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE playlistsongs (
    playlistid integer NOT NULL,
    songid integer NOT NULL,
    addedat timestamp with time zone NOT NULL,
    position integer NOT NULL,
    CONSTRAINT "PK_playlistsongs" PRIMARY KEY (playlistid, songid),
    CONSTRAINT "FK_playlistsongs_playlists_playlistid" FOREIGN KEY (playlistid) REFERENCES playlists (playlistid) ON DELETE CASCADE,
    CONSTRAINT "FK_playlistsongs_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE
);

CREATE TABLE comment_likes (
    likeid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    commentid integer NOT NULL,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_comment_likes" PRIMARY KEY (likeid),
    CONSTRAINT "FK_comment_likes_comments_commentid" FOREIGN KEY (commentid) REFERENCES comments (commentid) ON DELETE CASCADE,
    CONSTRAINT "FK_comment_likes_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE INDEX "IX_albumartists_artistid" ON albumartists (artistid);

CREATE INDEX "IX_albums_title" ON albums (title);

CREATE INDEX "IX_artist_followers_artistid" ON artist_followers (artistid);

CREATE UNIQUE INDEX "IX_artists_name" ON artists (name);

CREATE INDEX "IX_comment_likes_commentid" ON comment_likes (commentid);

CREATE INDEX "IX_comment_likes_userid" ON comment_likes (userid);

CREATE INDEX "IX_comments_songid" ON comments (songid);

CREATE INDEX "IX_comments_userid" ON comments (userid);

CREATE INDEX "IX_listeninghistory_songid" ON listeninghistory (songid);

CREATE INDEX "IX_listeninghistory_userid" ON listeninghistory (userid);

CREATE INDEX "IX_notifications_userid" ON notifications (userid);

CREATE INDEX "IX_payments_planid" ON payments (planid);

CREATE INDEX "IX_payments_userid" ON payments (userid);

CREATE INDEX "IX_playlists_userid" ON playlists (userid);

CREATE INDEX "IX_playlistsongs_songid" ON playlistsongs (songid);

CREATE INDEX "IX_reports_userid" ON reports (userid);

CREATE INDEX "IX_songartists_artistid" ON songartists (artistid);

CREATE INDEX "IX_songgenres_genreid" ON songgenres (genreid);

CREATE INDEX "IX_songlikes_songid" ON songlikes (songid);

CREATE INDEX "IX_songs_albumid" ON songs (albumid);

CREATE INDEX "IX_songs_categoryid" ON songs (categoryid);

CREATE INDEX "IX_songs_title_albumid" ON songs (title, albumid);

CREATE INDEX "IX_songs_youtubevideoid" ON songs (youtubevideoid);

CREATE INDEX "IX_user_subscriptions_planid" ON user_subscriptions (planid);

CREATE INDEX "IX_user_subscriptions_userid" ON user_subscriptions (userid);

CREATE INDEX "IX_usersearchhistory_userid" ON usersearchhistory (userid);

CREATE INDEX "IX_usersessions_userid" ON usersessions (userid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406134121_InitialCreate', '10.0.5');

COMMIT;

