-- Script cập nhật Database có kiểm tra tồn tại
START TRANSACTION;

-- 1. Thêm các cột thiếu vào users nếu chưa có
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='username') THEN
        ALTER TABLE users ADD COLUMN username varchar(100);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='email') THEN
        ALTER TABLE users ADD COLUMN email varchar(255);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='passwordhash') THEN
        ALTER TABLE users ADD COLUMN passwordhash text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='role') THEN
        ALTER TABLE users ADD COLUMN role varchar(50) DEFAULT 'Customer';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='createdat') THEN
        ALTER TABLE users ADD COLUMN createdat timestamp with time zone DEFAULT now();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='ispremium') THEN
        ALTER TABLE users ADD COLUMN ispremium boolean NOT NULL DEFAULT FALSE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='googleid') THEN
        ALTER TABLE users ADD COLUMN googleid text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='avatarurl') THEN
        ALTER TABLE users ADD COLUMN avatarurl text;
    END IF;
END $$;

-- Cho phép cột mật khẩu được phép để trống (dành cho đăng nhập Google)
ALTER TABLE users ALTER COLUMN passwordhash DROP NOT NULL;

-- 2. Tạo các bảng nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS listeninghistory (
    historyid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    songid integer NOT NULL,
    listenedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_listeninghistory" PRIMARY KEY (historyid),
    CONSTRAINT "FK_listeninghistory_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE,
    CONSTRAINT "FK_listeninghistory_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlists (
    playlistid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    coverimageurl text,
    createdat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_playlists" PRIMARY KEY (playlistid),
    CONSTRAINT "FK_playlists_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscription_plans (
    planid integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    price numeric NOT NULL,
    duration_days integer NOT NULL,
    description text,
    CONSTRAINT "PK_subscription_plans" PRIMARY KEY (planid)
);

CREATE TABLE IF NOT EXISTS usersearchhistory (
    searchid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    searchquery character varying(255) NOT NULL,
    searchedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_usersearchhistory" PRIMARY KEY (searchid),
    CONSTRAINT "FK_usersearchhistory_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlistsongs (
    playlistid integer NOT NULL,
    songid integer NOT NULL,
    addedat timestamp with time zone NOT NULL,
    CONSTRAINT "PK_playlistsongs" PRIMARY KEY (playlistid, songid),
    CONSTRAINT "FK_playlistsongs_playlists_playlistid" FOREIGN KEY (playlistid) REFERENCES playlists (playlistid) ON DELETE CASCADE,
    CONSTRAINT "FK_playlistsongs_songs_songid" FOREIGN KEY (songid) REFERENCES songs (songid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    paymentid integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    planid integer NOT NULL,
    amount numeric NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    status character varying(50) NOT NULL,
    order_code bigint NOT NULL DEFAULT 0,
    payos_transaction_id text,
    CONSTRAINT "PK_payments" PRIMARY KEY (paymentid),
    CONSTRAINT "FK_payments_subscription_plans_planid" FOREIGN KEY (planid) REFERENCES subscription_plans (planid) ON DELETE CASCADE,
    CONSTRAINT "FK_payments_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

-- Đồng bộ cột cho payments nếu bảng đã tồn tại từ trước
ALTER TABLE payments ADD COLUMN IF NOT EXISTS order_code bigint NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payos_transaction_id text;

CREATE TABLE IF NOT EXISTS user_subscriptions (
    user_subscription_id integer GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    planid integer NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_user_subscriptions" PRIMARY KEY (user_subscription_id),
    CONSTRAINT "FK_user_subscriptions_subscription_plans_planid" FOREIGN KEY (planid) REFERENCES subscription_plans (planid) ON DELETE CASCADE,
    CONSTRAINT "FK_user_subscriptions_users_userid" FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
);

-- 3. Tạo Index (sẽ bỏ qua nếu đã có)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_listeninghistory_songid') THEN
        CREATE INDEX "IX_listeninghistory_songid" ON listeninghistory (songid);
    END IF;
    -- Lặp lại tương tự cho các index khác nếu cần...
END $$;

COMMIT;
