using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YoutubeExplode;
using YoutubeExplode.Common;
using YoutubeExplode.Videos.ClosedCaptions;

namespace YoutubeLyricsProbe
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var youtube = new YoutubeClient();
            
            string[] testSongs = {
                "Adele Someone Like You",
                "Son Tung M-TP Lac Troi",
                "Ed Sheeran Shape of You"
            };

            Console.WriteLine("=== YOUTUBE LYRICS DYNAMIC PROBE ===");
            
            foreach (var songQuery in testSongs)
            {
                Console.WriteLine($"\n--- Testing: {songQuery} ---");
                try
                {
                    // 1. Search for video
                    Console.WriteLine($"[1/4] Searching for '{songQuery}'...");
                    var searchResults = await youtube.Search.GetVideosAsync(songQuery).CollectAsync(5);
                    
                    // Simple similarity check (optional but recommended in real app)
                    var video = searchResults.FirstOrDefault();
                    
                    if (video == null)
                    {
                        Console.WriteLine("Result: NOT_FOUND (No video matches)");
                        continue;
                    }

                    Console.WriteLine($"Found Video: {video.Title} ({video.Id})");

                    // 2. Load Captions
                    Console.WriteLine($"[2/4] Loading caption manifest...");
                    var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(video.Id);
                    
                    if (trackManifest.Tracks.Count == 0)
                    {
                        Console.WriteLine("Result: NOT_FOUND (No captions available)");
                        continue;
                    }

                    var trackInfo = trackManifest.TryGetByLanguage("vi") 
                                 ?? trackManifest.TryGetByLanguage("en")
                                 ?? trackManifest.Tracks.FirstOrDefault(t => t.IsAutoGenerated)
                                 ?? trackManifest.Tracks.FirstOrDefault();

                    if (trackInfo == null)
                    {
                        Console.WriteLine("Result: NOT_FOUND (No suitable language)");
                        continue;
                    }

                    Console.WriteLine($"Selected Track: {trackInfo.Language.Name} (Auto: {trackInfo.IsAutoGenerated})");

                    // 3. Parse Timed Lyrics
                    Console.WriteLine($"[3/4] Parsing Timed Captions...");
                    var track = await youtube.Videos.ClosedCaptions.GetAsync(trackInfo);
                    
                    var timedLines = track.Captions.Select(c => new
                    {
                        Start = c.Offset.TotalSeconds,
                        Duration = c.Duration.TotalSeconds,
                        Text = c.Text.Replace("\n", " ")
                    }).ToList();

                    if (timedLines.Count == 0)
                    {
                        Console.WriteLine("Result: NOT_FOUND (Captions exist but parsing failed)");
                        continue;
                    }

                    Console.WriteLine($"Result: SUCCESS ({timedLines.Count} timed lines found)");
                    
                    // Display Preview with Timestamps
                    Console.WriteLine("\n--- TIMED PREVIEW (First 5 lines) ---");
                    foreach (var line in timedLines.Take(5))
                    {
                        string timestamp = FormatTime(line.Start);
                        Console.WriteLine($"{timestamp} | {line.Text}");
                    }
                    Console.WriteLine("--------------------------------------\n");

                    // 4. Playback Simulation (Only for the first successful song to save time)
                    if (songQuery == testSongs[0])
                    {
                        await SimulatePlayback(timedLines);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Result: ERROR - {ex.Message}");
                }
            }
            
            Console.WriteLine("\n=== PROBE FINISHED ===");
        }

        static string FormatTime(double seconds)
        {
            var span = TimeSpan.FromSeconds(seconds);
            return $"[{span.Minutes:D2}:{span.Seconds:D2}.{span.Milliseconds:D3}]";
        }

        static async Task SimulatePlayback(IEnumerable<dynamic> lines)
        {
            Console.WriteLine(">>> STARTING REAL-TIME SIMULATION (First 30 seconds only) <<<");
            Console.WriteLine("Press any key to jump to results if you don't want to wait...");
            
            DateTime startTime = DateTime.Now;
            var lineList = lines.ToList();

            foreach (var line in lineList)
            {
                if (line.Start > 30) break; // Simulation cap for quick testing

                double elapsed = (DateTime.Now - startTime).TotalSeconds;
                double delay = line.Start - elapsed;

                if (delay > 0)
                {
                    await Task.Delay((int)(delay * 1000));
                }

                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.Write($"\r{FormatTime(line.Start)} ");
                Console.ResetColor();
                Console.WriteLine(line.Text);
                
                // Keep the last line summary
                if (Console.KeyAvailable) { Console.ReadKey(true); break; }
            }
            Console.WriteLine("\n>>> SIMULATION ENDED <<<\n");
        }
    }
}
